<?php
if ($this->data) {
    $tasks = $this->data;
    foreach ($tasks as $task) {
      echo '<div><ul>
      <li class="mt-4 ml-8 float-left block h-auto w-fit p-8 bg-yellow-200 opacity-75 shadow-2xl drop-shadow-lg shadow-stone-800">
        <p class="decoration-2 font-serif">Task Description:<br>'  . $task->task_description . '</p>
        <p class="decoration-2 font-serif">State: '  . $task->task_state . '</p>
        <br>
        <button class="bg-teal-700 border border-teal-800 shadow-xl shadow-stone-800 drop-shadow-2xl hover:bg-lime-500 hover:border-lime-500 rounded-lg"><a class="text-white hover:text-orange-600 font-mono" href="/web/show?id=' . $task->id . '">SHOW</a></button>
        <button class="bg-blue-700 border border-blue-800 shadow-xl shadow-stone-800 drop-shadow-2xl hover:bg-lime-500 hover:border-lime-500 rounded-lg"><a class="text-white hover:text-orange-600 font-mono" href="/web/update?id=' . $task->id . '">UPDATE</a></button>
        <button class="bg-red-700 border border-red-800 shadow-xl shadow-stone-800 drop-shadow-2xl hover:bg-lime-500 hover:border-lime-500 rounded-lg"><a class="text-white hover:text-orange-600 font-mono" href="/web/delete?id=' . $task->id . '">DELETE</a></button>
      </ul></div>';
    }
} ?>
