<?php
if ($this->data) {
    $tasks = $this->data;
    foreach ($tasks as $task) {
        // cast the DateTime objects to strings, formatting them
        $_start = new DateTime($task->date_time_start);
        $_start = $_start->format('d-m-Y H:i');
        $_end = new DateTime($task->date_time_end);
        $_end = $_end->format('d-m-Y H:i');
        echo '<div><ul>
        <li class="ml-8 float-left block h-auto w-fit p-8 bg-yellow-200 opacity-75 shadow-2xl drop-shadow-lg shadow-stone-800">
          <p class="decoration-2 font-serif">Task Description:<br>'  . $task->task_description . '</p>
          <p class="decoration-2 font-serif">State: '  . $task->task_state . '</p>
          <br>
          <button class="bg-teal-700 border border-teal-800 shadow-xl shadow-stone-800 drop-shadow-2xl hover:bg-lime-500 hover:border-lime-500 rounded-lg"><a class="text-white hover:text-orange-600 font-mono" href="show?id=' . $task->id . '">SHOW</a></button>
      </ul></div>';
    }
} ?>
