<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>ADD TASK</title>
	<script src="https://cdn.tailwindcss.com/?plugings=typography,forms"></script>
</head>
<body>
<h3>TASK LIST</h3>
<div style = "margin: 20px;">
<?php

if ($this->data) {
    $tasks = $this->data;
    foreach ($tasks as $task) {
        // cast the DateTime objects to strings, formatting them
        $_start = new DateTime($task->date_time_start);
        $_start = $_start->format('d-m-Y H:i');
        $_end = new DateTime($task->date_time_end);
        $_end = $_end->format('d-m-Y H:i');
        echo '<ul>
        <li class="m-11 float-left block h-auto w-fit p-4 bg-yellow-200 opacity-75 shadow-2xl drop-shadow-lg shadow-stone-800">
          <p class="decoration-2 font-serif">Task Description:<br>'  . $task->task_description . '</p>
          <p class="decoration-2 font-serif">Start: ' . $_start . '</p>
          <p class="decoration-2 font-serif">End: ' . $_end . '</p>
          <p class="decoration-2 font-serif">State: '  . $task->task_state . '</p>
          <p class="decoration-2 font-serif">User: '  . $task->user_first_name . ' ' . $task->user_last_name .  '</p>
          <br>
          <button class="bg-teal-700 border border-teal-800 shadow-xl shadow-stone-800 drop-shadow-2xl hover:bg-lime-500 hover:border-lime-500 rounded-lg"><a class="text-white hover:text-orange-600 font-mono" href="update">UPDATE</a></button>
          <button class="bg-red-600 border border-red-700 shadow-xl shadow-stone-800 drop-shadow-2xl hover:bg-lime-500 hover:border-lime-500 rounded-lg"><a class="text-white hover:text-orange-600 font-mono" href="delete">DELETE</a></button>
      </ul>';
    }
} ?>  
</div>
</body>
</html>