<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>UPDATE TASK</title>
	<script src="https://cdn.tailwindcss.com/?plugings=typography,forms"></script>
</head>
<body>
	<!-- header -->
	<div class="w-full fixed top-0 bg-orange-400 px-50 py-50">
		<div class="grid-cols-auto content-around">
			<nav class="ml-60 mr-0 mt-5 mb-5 place-self-auto grid-cols-auto content-around sm:aside">
				<button class="bg-green-500 border border-green-500 shadow-xl shadow-lime-200/50 drop-shadow-2xl hover:bg-lime-300 hover:border-lime-300 rounded-lg mr-8"><a class="hover:text-orange-600 font-mono" href="index">Home</a></button>
			</nav>
		</div>
	</div>
	<!-- content of the body -->
	<?php echo $this->content(); ?>
	<!-- footer -->
	<div class="w-full bg-orange-600 fixed bottom-0 px-400 py-200 pt-5">
    	<div class="container text-center text-white text-mono mb-5 mt-0">TODO List App by Developers Team</div>      
	</div>
</body>
</html>