<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>TASK LIST</title>
	<script src="https://cdn.tailwindcss.com/?plugings=typography,forms"></script>
</head>
<body class="bg-gradient-to-r from-green-100 via-emerald-200 to-teal-600">
	
	<!-- header -->
	<header class="bg-gradient-to-r from-lime-400 via-orange-300 to-orange-600 p-5">
		
		<button class="float-left bg-green-500 border border-green-500 shadow-xl shadow-lime-200/50 drop-shadow-2xl hover:bg-lime-300 hover:border-lime-300 rounded-lg w-24"><a class="hover:text-orange-600 font-mono" href="/index">Home</a></button>
		<h1 class="text-center uppercase text-xl text-lime-600 text-mono">task manager</h1>
		
	</header>
	<div class="bg-white p-2 "></div>
	<div class="overflow-auto flex flex-wrap">
	<!-- content of the body -->
	<?php echo $this->content(); //dentro este <div> se ha añadido scroll auto y posicionamiento flex?>
    </div>

	<!-- footer -->
	<section class="w-full fixed bottom-0">
	<div class="bg-white p-10"></div>
	<footer class="w-full bg-gradient-to-r from-orange-600 via-orange-300 to-lime-400 fixed bottom-0 px-400 py-200 pt-5">
    	<h2 class="text-center text-lime-800 text-mono mb-5 mt-0">TODO List App by Developers Team</h2>      
	</footer>
	</section>
	
</body>
</html>